branches:
  - name: gh-pages
    protection:
      allow_deletions: false
      allow_force_pushes: true
      block_creations: false
      enforce_admins: false
      required_conversation_resolution: false
      required_linear_history: true
      required_pull_request_reviews: null
      required_status_checks: null
      restrictions: null
  - name: main
    protection:
      allow_deletions: false
      allow_force_pushes: false
      block_creations: true
      enforce_admins: false
      required_conversation_resolution: true
      required_linear_history: true
      required_pull_request_reviews:
        dismiss_stale_reviews: true
        required_approving_review_count: 1
      required_status_checks:
        enforce_admins: false
        strict: true
      restrictions: null
collaborators:
  - username: logsworth
    permission: push
repository:
  allow_auto_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false
  allow_squash_merge: true
  allow_update_branch: true
  default_branch: main
  delete_branch_on_merge: true
  has_discussions: false
  has_downloads: false
  has_issues: false
  has_projects: false
  has_wiki: false
  is_template: false
  squash_merge_commit_message: COMMIT_MESSAGES
  squash_merge_commit_title: PR_TITLE
  visibility: public
